name: CMake Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Setup dependencies
      run: sudo apt install libusb-1.0-0-dev libboost-dev libboost-system-dev
    - name: Create build directory
      run: cmake -E make_directory ${{runner.workspace}}/build
    - name: configure
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE
    - name: build
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: cmake --build .
    - uses: actions/upload-artifact@v2
      with:
        name: executable
        path: ${{runner.workspace}}/build/spi_prog
